services:
  spark-master:
    image: spark:3.5.0-python3
    command: ../sbin/start-master.sh
    environment:
      - SPARK_NO_DAEMONIZE=${SPARK_NO_DAEMONIZE}
      - SPARK_MASTER_HOST=${SPARK_MASTER_HOST}
    ports:
      - 9090:8080
      - 7077:7077
    
  spark-worker-a:
    image: spark:3.5.0-python3
    environment:
      - SPARK_NO_DAEMONIZE=${SPARK_NO_DAEMONIZE}
      - SPARK_WORKER_WEBUI_PORT=9091
      - SPARK_WORKER_CORES=1
      - SPARK_WORKER_MEMORY=6G
      - SPARK_DRIVER_MEMORY=3G
    ports:
      - 9091:9091
    depends_on:
      - spark-master
    command: '../sbin/start-worker.sh ${SPARK_MASTER_HOST}:7077'

#  spark-worker-b:
#    image: spark:3.5.0-python3
#    environment:
#      - SPARK_NO_DAEMONIZE=${SPARK_NO_DAEMONIZE}
#      - SPARK_WORKER_WEBUI_PORT=9092
#      - SPARK_WORKER_CORES=1
#      - SPARK_WORKER_MEMORY=4G
#      - SPARK_DRIVER_MEMORY=4G
#      - SPARK_EXECUTOR_MEMORY=4G
#    depends_on:
#      - spark-master
#    command: '../sbin/start-worker.sh ${SPARK_MASTER_HOST}:7077'
  
#  postgres:
#    image: postgres:15
#    hostname: demo_db
#    ports:
#      - 5432:5432
#    volumes:
#      - ./db/demo_db.sql:/demo_db.sql
#      - ./db/restore.sh:/docker-entrypoint-initdb.d/restore.sh
#    environment:
#      - POSTGRES_PASSWORD=${DB_PASSWORD}
#      - POSTGRES_USER=${DB_USER}
#      - POSTGRES_DB=${DB_NAME}
  
#  jupyter:
#    build: ./src/
#    volumes:
#      - ./src:/app
#    ports:
#      - 8888:8888


    


    
